pre_bump_hooks = [
    "echo Current: {{latest}}",
    "echo Next: {{version}}",
    "echo Patching be",
    "cd be && sed -i 's/version: {{latest}}/version: {{version}}/g' package.yaml && hpack",
    "echo Patching fe",
    "cd fe && sed -i 's/index.js?v={{latest}}/index.js?v={{version}}/g' ./dev/index.html",
    "cd fe && sed -i 's/version = \"{{latest}}\"/version = \"{{version}}\"/g' ./src/Main.purs"
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "simple-lists"
owner = "michalgcc"
authors = [
  { signature = "Michal Gasz", username = "michalgcc" }
]

[git_hooks.pre-commit]
script = """#!/usr/bin/env bash
set -e
pushd be
./format_code.sh
popd
pushd fe
./format_code.sh
popd
"""

[git_hooks.commit-msg]
script = """#!/usr/bin/env bash
set -e
cog verify --file $1
cog check
"""
