version: "3.8"

name: simple-lists

services:
  simple-lists:
    container_name: simple-lists
    image: ghcr.io/michalgcc/simple-lists:latest
    environment:
      - ALLOWED_CORS_ORIGINS_COMMA_SEPARATED:http://localhost:9292
    volumes:
      - data:/var/app_db/
    ports:
      - 9292:9292
    restart: always

volumes:
  data: